* Jour 6 : Garde Gallivant
Les historiens utilisent à nouveau leur appareil sophistiqué, cette fois pour vous emmener tous au laboratoire de fabrication du prototype de combinaison du pôle Nord... en l'an 1518 ! Il s'avère qu'avoir un accès direct à l'histoire est très pratique pour un groupe d'historiens.

Vous devez toujours faire attention aux paradoxes temporels, et il sera donc important d'éviter toute personne de 1518 pendant que les historiens recherchent le chef. Malheureusement, un seul garde patrouille dans cette partie du laboratoire.

Peut-être pouvez-vous déterminer à l'avance où le garde ira pour que les historiens puissent chercher en toute sécurité ?

Vous commencez par faire une carte (votre entrée de puzzle) de la situation. Par exemple :

....#.....
........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
La carte indique la position actuelle du garde avec ^ (pour indiquer que le garde est actuellement tourné vers le haut depuis la perspective de la carte). Tous les obstacles - caisses, bureaux, réacteurs alchimiques, etc. - sont indiqués par #.

Les gardes du laboratoire de 1518 suivent un protocole de patrouille très strict qui implique de suivre à plusieurs reprises ces étapes :

S'il y a quelque chose directement devant vous, tournez à droite de 90 degrés.
Sinon, faites un pas en avant.
En suivant le protocole ci-dessus, le garde monte plusieurs fois jusqu'à atteindre un obstacle (dans ce cas, une pile de prototypes de combinaisons défaillantes) :

....#.....
....^....#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#...
Parce qu'il y a maintenant un obstacle devant le garde, elle tourne à droite avant de continuer tout droit dans sa nouvelle direction :

....#.....
........>#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#...
En atteignant un autre obstacle (une bobine de plusieurs polymères très longs), elle tourne à nouveau à droite et continue vers le bas :

....#.....
.........#
..........
..#.......
.......#..
..........
.#......v.
........#.
#.........
......#...
Ce processus continue pendant un certain temps, mais le garde quitte finalement la zone cartographiée (après être passé devant un réservoir de solvant universel) :

....#.....
.........#
..........
..#.......
.......#..
..........
.#........
........#.
#.........
......#v..
En prédisant l'itinéraire du garde, vous pouvez déterminer quelles positions spécifiques du laboratoire se trouveront sur le chemin de la patrouille. En incluant la position de départ du garde, les positions visitées par le garde avant de quitter la zone sont marquées d'un X :

....#.....
....XXXXX#
....X...X.
..#.X...X.
..XXXXX#X.
..X.X.X.X.
.#XXXXXXX.
.XXXXXXX#.
#XXXXXXX..
......#X..
Dans cet exemple, le garde visitera 41 positions distinctes sur votre carte.

Prédisez le chemin du garde. Combien de positions distinctes le garde visitera-t-il avant de quitter la zone cartographiée ?

** Réponse : ~4964~

* Deuxième partie 
Pendant que les historiens commencent à travailler autour de l'itinéraire de patrouille du garde, vous empruntez leur appareil sophistiqué et sortez du laboratoire. Depuis la sécurité d'un placard de fournitures, vous voyagez dans le temps à travers les derniers mois et enregistrez l'état nocturne du poste de garde du laboratoire sur les murs du placard.

De retour après ce qui semble n'être que quelques secondes, les historiens expliquent que la zone de patrouille du garde est tout simplement trop grande pour qu'ils puissent fouiller le laboratoire en toute sécurité sans se faire prendre.

Heureusement, ils sont à peu près sûrs que l'ajout d'une seule nouvelle obstruction ne provoquera pas de paradoxe temporel. Ils aimeraient placer la nouvelle obstruction de telle manière que le garde se retrouve coincé dans une boucle, ce qui rendrait le reste du laboratoire sûr pour la recherche.

Pour avoir le moins de chances de créer un paradoxe temporel, les historiens aimeraient connaître toutes les positions possibles pour une telle obstruction. La nouvelle obstruction ne peut pas être placée à la position de départ du garde - le garde est là en ce moment et le remarquerait.

Dans l'exemple ci-dessus, il n'y a que 6 positions différentes où une nouvelle obstruction pourrait faire que le garde reste coincé dans une boucle. Les diagrammes de ces six situations utilisent O pour marquer la nouvelle obstruction, | pour montrer une position où le garde se déplace vers le haut/bas, - pour montrer une position où le garde se déplace vers la gauche/droite, et + pour montrer une position où le garde se déplace à la fois vers le haut/bas et vers la gauche/droite.

Première option, placez une presse à imprimer à côté de la position de départ du garde :

....#.....
....+---+#
....|...|.
..#.|...|.
....|..#|.
....|...|.
.#.O^---+.
........#.
#.........
......#...
Option deux, placez une pile de prototypes de combinaisons défaillantes dans le quadrant inférieur droit de la zone cartographiée :

....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
......O.#.
#.........
......#...
Option trois, placez une caisse de tissu prototype à compression de cheminée à côté du bureau debout dans le quadrant inférieur droit :

....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
.+----+O#.
#+----+...
......#...
Option quatre, placez un rétroencabulateur alchimique près du coin inférieur gauche :

....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
..|...|.#.
#O+---+...
......#...
Option cinq, placez plutôt le rétroencabulateur alchimique un peu à droite :

....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
....|.|.#.
#..O+-+...
......#...
Option six, placez un réservoir de colle souveraine juste à côté du réservoir de solvant universel :

....#.....
....+---+#
....|...|.
..#.|...|.
..+-+-+#|.
..|.|.|.|.
.#+-^-+-+.
.+----++#.
#+----++..
......#O..
Peu importe ce que vous choisissez d'utiliser comme obstacle tant que vous et les historiens pouvez le mettre en place sans que le garde ne s'en aperçoive. L'important est d'avoir suffisamment d'options pour pouvoir en trouver une qui minimise les paradoxes temporels, et dans cet exemple, il y a 6 positions différentes que vous pouvez choisir.

Vous devez bloquer le garde dans une boucle en ajoutant une seule nouvelle obstruction. Combien de positions différentes pourriez-vous choisir pour cette obstruction ?

** Réponse : ~1740~

