* Jour 5 : File d'attente d'impression
** Première Partie
Satisfait de sa recherche sur Cérès, l'escadron d'érudits suggère de scanner ensuite les piles de papeterie du sous-sol 17.

Le service d'impression du pôle Nord est plus occupé que jamais à l'approche de Noël, et tandis que les historiens continuent leur recherche de cette installation historiquement importante, un elfe qui utilise une imprimante très familière vous fait signe.

L'elfe doit vous reconnaître, car il ne perd pas de temps à vous expliquer que les nouvelles mises à jour du manuel de sécurité du lancement du traîneau ne s'imprimeront pas correctement. Ne pas mettre à jour les manuels de sécurité serait vraiment désastreux, alors vous proposez vos services.

Les protocoles de sécurité indiquent clairement que les nouvelles pages des manuels de sécurité doivent être imprimées dans un ordre très spécifique. La notation X|Y signifie que si les pages numérotées X et Y doivent être produites dans le cadre d'une mise à jour, la page numérotée X doit être imprimée à un moment donné avant la page numérotée Y.

L'elfe a pour vous les règles d'ordre des pages et les pages à produire dans chaque mise à jour (votre entrée de puzzle), mais ne peut pas déterminer si chaque mise à jour a les pages dans le bon ordre.

Par exemple :

47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47
La première section spécifie les règles d'ordre des pages, une par ligne. La première règle, 47|53, signifie que si une mise à jour comprend à la fois la page 47 et la page 53, la page 47 doit être imprimée à un moment donné avant la page 53. (La page 47 ne doit pas nécessairement être immédiatement avant la page 53 ; d'autres pages peuvent être placées entre elles.)

La deuxième section précise les numéros de page de chaque mise à jour. Étant donné que la plupart des manuels de sécurité sont différents, les pages nécessaires aux mises à jour sont également différentes. La première mise à jour, 75,47,61,53,29, signifie que la mise à jour comprend les pages 75, 47, 61, 53 et 29.

Pour que les imprimantes fonctionnent le plus rapidement possible, commencez par identifier les mises à jour qui sont déjà dans le bon ordre.

Dans l'exemple ci-dessus, la première mise à jour (75,47,61,53,29) est dans le bon ordre :

75 est correctement placé en premier car il existe des règles qui placent chaque page après elle : 75|47, 75|61, 75|53 et 75|29.
47 est correctement placé en deuxième car 75 doit être placé avant elle (75|47) et toutes les autres pages doivent être placées après elle conformément à 47|61, 47|53 et 47|29.
61 est correctement placé au milieu car 75 et 47 sont placés avant elle (75|61 et 47|61) et 53 et 29 sont placés après elle (61|53 et 61|29).
53 est correctement placé en quatrième car il est placé avant la page numéro 29 (53|29).
29 est la seule page restante et est donc correctement placé en dernier.
Étant donné que la première mise à jour n'inclut pas certains numéros de page, les règles de classement impliquant ces numéros de page manquants sont ignorées.

Les deuxième et troisième mises à jour sont également dans le bon ordre selon les règles. Comme la première mise à jour, elles n'incluent pas non plus tous les numéros de page, et donc seules certaines des règles de classement s'appliquent - dans chaque mise à jour, les règles de classement impliquant des numéros de page manquants ne sont pas utilisées.

La quatrième mise à jour, 75,97,47,61,53, n'est pas dans le bon ordre : elle imprimerait 75 avant 97, ce qui viole la règle 97|75.

La cinquième mise à jour, 61,13,29, n'est pas non plus dans le bon ordre, car elle enfreint la règle 29|13.

La dernière mise à jour, 97,13,75,29,47, n'est pas dans le bon ordre en raison de la violation de plusieurs règles.

Pour une raison quelconque, les elfes doivent également connaître le numéro de page du milieu de chaque mise à jour imprimée. Étant donné que vous n'imprimez actuellement que les mises à jour correctement ordonnées, vous devrez trouver le numéro de page du milieu de chaque mise à jour correctement ordonnée. Dans l'exemple ci-dessus, les mises à jour correctement ordonnées sont :

75,47,61,53,29
97,61,53,29,13
75,29,13
Ces mises à jour ont respectivement les numéros de page du milieu 61, 53 et 29. L'addition de ces numéros de page donne 143.

Bien sûr, vous devrez faire attention : la liste réelle des règles d'ordre des pages est plus longue et plus compliquée que l'exemple ci-dessus.

Déterminez quelles mises à jour sont déjà dans le bon ordre. Qu'obtenez-vous si vous additionnez le numéro de page du milieu de ces mises à jour correctement ordonnées ?

*** Réponse : ~4689~

** Deuxième partie
Pendant que les elfes se mettent au travail pour imprimer les mises à jour correctement ordonnées, vous avez un peu de temps pour corriger le reste.

Pour chacune des mises à jour mal ordonnées, utilisez les règles d'ordre des pages pour mettre les numéros de page dans le bon ordre. Pour l'exemple ci-dessus, voici les trois mises à jour mal ordonnées et leur ordre correct :

75,97,47,61,53 devient 97,75,47,61,53.
61,13,29 devient 61,29,13.
97,13,75,29,47 devient 97,75,47,29,13.
Après avoir pris uniquement les mises à jour mal ordonnées et les avoir ordonnées correctement, leurs numéros de page du milieu sont 47, 29 et 47. En les additionnant, on obtient 123.

Trouvez les mises à jour qui ne sont pas dans le bon ordre. Qu'obtenez-vous si vous additionnez les numéros de page du milieu après avoir correctement commandé uniquement ces mises à jour ?

*** Réponse : ~6336~
