* Jour 1 : Hystérie de l'historien
L'historien en chef est toujours présent pour le grand lancement du traîneau de Noël, mais personne ne l'a vu depuis des mois ! La dernière fois que quelqu'un a entendu parler de lui, il visitait des lieux historiquement importants pour le pôle Nord ; un groupe d'historiens seniors vous a demandé de les accompagner pendant qu'ils vérifient les endroits qu'ils pensent qu'il était le plus susceptible de visiter.

A chaque fois qu'ils vérifient un lieu, ils le marquent sur leur liste d'une étoile. Ils pensent que l'historien en chef doit être dans l'un des cinquante premiers endroits qu'ils vont regarder, donc pour sauver Noël, vous devez les aider à obtenir cinquante étoiles sur leur liste avant le départ du Père Noël le 25 décembre.

Collectez des étoiles en résolvant des énigmes. Deux énigmes seront disponibles chaque jour dans le calendrier de l'Avent ; la deuxième énigme est débloquée lorsque vous terminez la première. Chaque énigme accorde une étoile. Bonne chance !

Vous n'êtes même pas encore parti que le groupe d'historiens seniors elfiques a déjà rencontré un problème : sa liste d'endroits à vérifier est actuellement vide. Finalement, quelqu'un décide que le meilleur endroit pour vérifier en premier serait le bureau de l'historien en chef.

En entrant dans le bureau, tout le monde confirme que l'historien en chef est effectivement introuvable. Au lieu de cela, les elfes découvrent un assortiment de notes et de listes de lieux historiques importants ! Cela semble être la planification que l'historien en chef faisait avant de partir. Peut-être que ces notes peuvent être utilisées pour déterminer les lieux à rechercher ?

Dans tout le bureau du chef, les lieux historiques importants ne sont pas répertoriés par nom mais par un numéro unique appelé identifiant de lieu. Pour s'assurer qu'ils ne manquent rien, les historiens se divisent en deux groupes, chacun fouillant dans le bureau et essayant de créer sa propre liste complète d'identifiants de lieux.

Il y a juste un problème : en tenant les deux listes côte à côte (votre saisie de puzzle), il devient rapidement évident que les listes ne sont pas très similaires. Peut-être pouvez-vous aider les historiens à réconcilier leurs listes ?

Par exemple :

3 4
4 3
2 5
1 3
3 9
3 3
Peut-être que les listes ne sont décalées que d'un petit nombre ! Pour le savoir, associez les nombres et mesurez leur distance. Associez le plus petit nombre de la liste de gauche au plus petit nombre de la liste de droite, puis le deuxième plus petit nombre de gauche au deuxième plus petit nombre de droite, et ainsi de suite.

Dans chaque paire, déterminez la distance qui sépare les deux nombres ; vous devrez additionner toutes ces distances. Par exemple, si vous associez un 3 de la liste de gauche à un 7 de la liste de droite, la distance est de 4 ; si vous associez un 9 à un 3, la distance qui les sépare est de 6.

Dans l'exemple de liste ci-dessus, les paires et les distances seraient les suivantes :

Le plus petit nombre de la liste de gauche est 1, et le plus petit nombre de la liste de droite est 3. La distance qui les sépare est de 2.
Le deuxième plus petit nombre de la liste de gauche est 2, et le deuxième plus petit nombre de la liste de droite est un autre 3. La distance qui les sépare est de 1.
Le troisième plus petit nombre des deux listes est 3, donc la distance qui les sépare est de 0.
Les prochains nombres à associer sont 3 et 4, soit une distance de 1.
Les cinquièmes plus petits nombres de chaque liste sont 3 et 5, soit une distance de 2.
Enfin, le plus grand nombre de la liste de gauche est 4, tandis que le plus grand nombre de la liste de droite est 9 ; ils sont à une distance de 5.
Pour trouver la distance totale entre la liste de gauche et la liste de droite, additionnez les distances entre toutes les paires que vous avez trouvées. Dans l'exemple ci-dessus, cela correspond à 2 + 1 + 0 + 1 + 2 + 5, soit une distance totale de 11 !

Vos listes de gauche et de droite contiennent de nombreux identifiants d'emplacement. Quelle est la distance totale entre vos listes ?

** Réponse: 1970720

* Deuxième partie
Votre analyse n'a fait que confirmer ce que tout le monde craignait : les deux listes d'identifiants de lieux sont en effet très différentes.

Ou le sont-elles ?

Les historiens ne parviennent pas à se mettre d'accord sur le groupe qui a commis les erreurs ou sur la façon de lire la plupart de l'écriture manuscrite du chef, mais dans le tumulte, vous remarquez un détail intéressant : de nombreux identifiants de lieux apparaissent dans les deux listes ! Peut-être que les autres numéros ne sont pas du tout des identifiants de lieux mais plutôt une écriture manuscrite mal interprétée.

Cette fois, vous devrez déterminer exactement à quelle fréquence chaque numéro de la liste de gauche apparaît dans la liste de droite. Calculez un score de similarité total en additionnant chaque numéro de la liste de gauche après l'avoir multiplié par le nombre de fois que ce numéro apparaît dans la liste de droite.

Voici à nouveau les mêmes exemples de listes :

3 4
4 3
2 5
1 3
3 9
3 3
Pour ces exemples de listes, voici le processus de recherche du score de similarité :

Le premier nombre de la liste de gauche est 3. Il apparaît trois fois dans la liste de droite, donc le score de similarité augmente de 3 * 3 = 9.
Le deuxième nombre de la liste de gauche est 4. Il apparaît une fois dans la liste de droite, donc le score de similarité augmente de 4 * 1 = 4.
Le troisième nombre de la liste de gauche est 2. Il n'apparaît pas dans la liste de droite, donc le score de similarité n'augmente pas (2 * 0 = 0).
Le quatrième nombre, 1, n'apparaît pas non plus dans la liste de droite.
Le cinquième nombre, 3, apparaît trois fois dans la liste de droite ; le score de similarité augmente de 9.
Le dernier nombre, 3, apparaît trois fois dans la liste de droite ; le score de similarité augmente à nouveau de 9.
Ainsi, pour ces exemples de listes, le score de similarité à la fin de ce processus est de 31 (9 + 4 + 0 + 0 + 9 + 9).

Considérez à nouveau vos listes de gauche et de droite. Quel est leur score de similarité ?

** Réponse: 17191599


