* Jour 8 : Colinéarité résonnante
** Première Partie
Vous vous trouvez sur le toit d'une installation top-secrète de lapins de Pâques.

Pendant que les historiens font leur travail, vous jetez un œil à l'énorme antenne familière. À votre grande surprise, elle semble avoir été reconfigurée pour émettre un signal qui augmente de 0,1 % la probabilité que les gens achètent du chocolat médiocre d'imitation de marque Easter Bunny comme cadeau de Noël ! Impensable !

En parcourant la ville du regard, vous découvrez qu'il existe en fait de nombreuses antennes de ce type. Chaque antenne est réglée sur une fréquence spécifique indiquée par une seule lettre minuscule, majuscule ou chiffre. Vous créez une carte (votre entrée de puzzle) de ces antennes. Par exemple :

............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
..........A..
............
............
Le signal n'applique son effet néfaste qu'à des antinœuds spécifiques en fonction des fréquences de résonance des antennes. En particulier, un ventre de nœud apparaît à tout point qui est parfaitement aligné avec deux antennes de la même fréquence - mais seulement lorsque l'une des antennes est deux fois plus éloignée que l'autre. Cela signifie que pour toute paire d'antennes de même fréquence, il y a deux ventres de nœud, un de chaque côté d'elles.

Ainsi, pour ces deux antennes de fréquence a, elles créent les deux ventres de nœud marqués d'un # :

..........
...#......
..........
....a.....
..........
.....a....
..........
......#...
..........
..........
L'ajout d'une troisième antenne de la même fréquence crée plusieurs ventres de nœuds supplémentaires. Idéalement, cela ajouterait quatre ventres de nœud, mais deux sont à droite de la carte, donc à la place, cela n'en ajoute que deux :

..........
...#......
#.........
....a.....
........a.
.....a....
..#.......
......#...
..........
..........
Les antennes avec des fréquences différentes ne créent pas de ventres de nœud ; A et a sont considérés comme des fréquences différentes. Cependant, des ventres peuvent apparaître à des emplacements contenant des antennes. Dans ce diagramme, l'antenne isolée avec la fréquence A majuscule ne crée aucun ventre mais possède un ventre de fréquence a minuscule à son emplacement :

..........
...#......
#.........
....a....
........a.
.....a....
..#.......
......A...
..........
..........
Le premier exemple comporte des antennes avec deux fréquences différentes, donc les ventres qu'elles créent ressemblent à ceci, plus un ventre chevauchant l'antenne de fréquence A la plus haute :

......#....#
...#....0...
....#0....#.
..#....0....
....0....#..
.#....A.....
...#........
#......#....
........A...
.........A..
..........#.
..........#.
Étant donné que l'antenne de fréquence A la plus haute chevauche un antinœud de fréquence 0, il existe au total 14 emplacements uniques qui contiennent un antinœud dans les limites de la carte.

Calculez l'impact du signal. Combien d'emplacements uniques dans les limites de la carte contiennent un antinœud ?

*** Réponse : ~313~

** Deuxième partie 
En regardant par-dessus votre épaule pendant que vous travaillez, l'un des historiens vous demande si vous avez pris en compte les effets des harmoniques résonnantes dans vos calculs.

Oups !

Après avoir mis à jour votre modèle, il s'avère qu'un antinœud se produit à n'importe quelle position de la grille exactement en ligne avec au moins deux antennes de la même fréquence, quelle que soit la distance. Cela signifie que certains des nouveaux antinœuds se produiront à la position de chaque antenne (à moins que cette antenne ne soit la seule de sa fréquence).

Ainsi, ces trois antennes de fréquence T créent maintenant de nombreux antinœuds :

T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........
En fait, les trois antennes de fréquence T sont toutes exactement en ligne avec deux antennes, elles sont donc toutes aussi des antinœuds ! Cela porte le nombre total d'antinœuds dans l'exemple ci-dessus à 9.

L'exemple original comporte désormais 34 antinœuds, y compris les antinœuds qui apparaissent sur chaque antenne :

##....#....#
.#.#....0...
..#.#0....#.
..##...0........0....#..
.#...#A....#
...#..#.....
#....#.#....
..#.....A...
....#....A..
.#........#.
...#......##
Calculez l'impact du signal à l'aide de ce modèle mis à jour. Combien d'emplacements uniques dans les limites de la carte contiennent un antinœud ?

*** Réponse : ~1064~
