* Jour 2: Une histoire de renne au nez rouge
** Première partie
Heureusement, le premier endroit que les historiens veulent fouiller n'est pas loin du bureau de l'historien
en chef.

Bien que l'usine de fusion/fission nucléaire du Renne au nez rouge ne semble contenir aucun signe de
l'historien en chef, les ingénieurs qui s'y trouvent courent vers vous dès qu'ils vous voient. Apparemment,
ils parlent encore de l'époque où Rudolph a été sauvé par synthèse moléculaire à partir d'un seul électron.

Ils s'empressent d'ajouter que --- puisque vous êtes déjà là --- ils apprécieraient vraiment votre aide pour
analyser certaines données inhabituelles du réacteur au nez rouge. Vous vous retournez pour vérifier si les
historiens vous attendent, mais ils semblent déjà s'être divisés en groupes qui fouillent actuellement tous
les recoins de l'installation. Vous proposez de les aider à analyser les données inhabituelles.

Les données inhabituelles (votre entrée de puzzle) se composent de plusieurs rapports, un rapport par
ligne. Chaque rapport est une liste de nombres appelés niveaux qui sont séparés par des espaces. Par
exemple:

#+begin_example
7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
#+end_example

Ces données d'exemple contiennent six rapports contenant chacun cinq niveaux.

Les ingénieurs tentent de déterminer quels rapports sont sûrs. Les systèmes de sécurité du réacteur
Red-Nosed ne peuvent tolérer que des niveaux qui augmentent ou diminuent progressivement. Ainsi, un rapport
n'est considéré comme sûr que si les deux conditions suivantes sont remplies:

Les niveaux augmentent tous ou diminuent tous.  Deux niveaux adjacents diffèrent d'au moins un et d'au plus
trois.  Dans l'exemple ci-dessus, les rapports peuvent être jugés sûrs ou non en vérifiant ces règles:

#+begin_example
7 6 4 2 1: Sûr car les niveaux diminuent tous de 1 ou 2.
1 2 7 8 9: Non sûr car 2 7 correspond à une augmentation de 5.
9 7 6 2 1: Non sûr car 6 2 correspond à une diminution de 4.
1 3 2 4 5: Non sûr car 1 3 augmente mais 3 2 diminue.
8 6 4 4 1: Non sûr car 4 4 n'est ni une augmentation ni une diminution.
1 3 6 7 9: Sûr car les niveaux augmentent tous de 1, 2 ou 3.
#+end_example

Donc, dans cet exemple, 2 rapports sont sûrs.

Analysez les données inhabituelles des ingénieurs. Combien de rapports sont sûrs?

*** Réponse: ~230~

** Deuxième partie
Les ingénieurs sont surpris par le faible nombre de rapports sûrs jusqu'à ce qu'ils réalisent qu'ils ont
oublié de vous parler de l'amortisseur de problèmes.

L'amortisseur de problèmes est un module monté sur le réacteur qui permet aux systèmes de sécurité du
réacteur de tolérer un seul niveau défectueux dans ce qui serait autrement un rapport sûr. C'est comme si le
niveau défectueux n'était jamais arrivé!

Maintenant, les mêmes règles s'appliquent qu'avant, sauf que si la suppression d'un seul niveau d'un rapport
non sûr le rendrait sûr, le rapport est alors considéré comme sûr.

Plus de rapports de l'exemple ci-dessus sont désormais sûrs:

#+begin_example
7 6 4 2 1 : Sûr sans supprimer aucun niveau.
1 2 7 8 9 : Non sûr quel que soit le niveau supprimé.
9 7 6 2 1 : Non sûr quel que soit le niveau supprimé.
1 3 2 4 5 : Sûr en supprimant le deuxième niveau, 3.
8 6 4 4 1 : Sûr en supprimant le troisième niveau, 4.
1 3 6 7 9 : Sûr sans supprimer aucun niveau.
#+end_example

Grâce à l'amortisseur de problèmes, 4 rapports sont désormais sûrs!

Mettez à jour votre analyse en gérant les situations dans lesquelles l'amortisseur de problèmes peut
supprimer un seul niveau des rapports non sûrs. Combien de rapports sont désormais sûrs?

*** Réponse: ~301~
